baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false
  author = "Monica Thieu"

[languages]
  [languages.en]
    title = "Monica Thieu"
    subtitle = "Research & goodies"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Monica Thieu"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "game-shows"
        name = "Game shows"
        url = "/game-shows"
      [[languages.en.menu.main]]
        identifier = "research"
        name = "Research"
        url = "/research"
