---
title: "Teaching roles and responsibilities"
weight: 3
description: "A summary of the teaching positions I've held."
output: 
  blogdown::html_page:
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Instructor of record

## PSY 417 -- Statistics II in Psychology

- Institution: Spelman College
- Term: spring 2024
- Supervisor contact: [Jimmeka Guillory Wright](mailto:jguillo1@spelman.edu)

### Course details

- Upper-level undergraduate class, satisfies Advanced Measurement requirement for psychology majors
- Statistics with a regression framework
- Analysis techniques taught in R/RStudio Cloud
- 25 students

### Instructional responsibilities

- Wrote curriculum
  - Defined learning objectives
  - Evaluated and selected readings
  - Wrote lesson plans, pre-class reading quizzes, and problem sets
  - Created teaching materials: slides, activity materials, R notebooks
- Lectured, live-coded, and supervised activities
- Graded assignments
  - Both multiple-choice/short answer assignments and R-based computational assignments
  - Gave detailed formative feedback on problem sets using single-point-style rubrics
- Held weekly office hours

## PSYC 1021 -- The Science of Psychology: Explorations and Applications

- Institution: Columbia University
- Term: summer 2022

### Course details

- Intro-level undergraduate class, satisfies core science requirement for non-majors
- 12 students, with learning teams of 4 students each

### Instructional responsibilities

- Updated curriculum
  - Defined learning objectives
  - Evaluated and selected readings
  - Edited lesson plans, pre-class quizzes, and assignment prompts
  - Created and edited teaching materials: slides, activity materials
- Lectured and led discussions
- Graded writing assignments
  - Gave detailed formative feedback on individual and group writing assignments and projects using single-point-style rubrics
- Held weekly office hours

---

# Instructor (non-credit courses)

## WiSTEM Data Science Lab Module

- Institution: Spelman College
- Term: summer 2022
- Program directors: [Monica Stephens](mailto:mstephens@spelman.edu), [Tiffany Oliver](mailto:toliver4@spelman.edu)

### Course details

- Offered as part of an application-only [6-week summer bridge accelerator](https://www.spelman.edu/academics/research-programs/wistem) for incoming STEM first-year students
- Full program includes enrollment in summer math and computer science courses for credit, and science lab courses not for credit (including this course)
- Students learned basic data manipulation and visualization skills in R and completed independent lab projects

### Instructional responsibilities

- Created curriculum
  - Defined learning objectives
  - Created all lesson plans and teaching materials
- Lectured, supervised lab work, and advised on independent projects

---

# Curriculum developer and co-instructor

## PSYC 1021 -- The Science of Psychology: Explorations and Applications

- Institution: Columbia University
- Term: spring 2021
- Lead instructor: [Caroline Marvin](mailto:cbm2118@columbia.edu)

### Course details

- As [above](#instructor-of-record)
- Approximately 30 students, with learning teams of approximately 4 students each

### Instructional responsibilities

- Developed curriculum, in conjunction with lead instructor
  - Defined learning objectives
  - Evaluated and selected readings
  - Wrote lesson plans, pre-class quizzes, and assignment prompts
  - Created teaching materials: slides, activity materials, mini-lecture videos
- Guest lecturing (approximately 1/4 of instructional modules)
- Graded writing assignments
  - Gave detailed formative feedback on individual and group writing assignments and projects using single-point-style rubrics
- Held weekly office hours

---

## Psychology department coding bootcamp

- Institution: Columbia University
- Terms: spring 2018, fall 2018, fall 2019, fall 2020, fall 2021

### Course details

- Unofficial open-enrollment workshop for psychology students at the undergrad level and above
- 5-20 students per session, depending on the semester

### Instructional responsibilities

- Curriculum development
  - Drafted lessons for 2 half-day sessions
  - Peer-reviewed 1 session lesson drafted by another co-instructor
- Lecture: Live-code lectured some or all of the lessons I prepared (depending on the semester)

---

# Section leader

## PSYC 1490 -- Research Methods in Psychology

- Institution: Columbia University
- Terms: fall 2018, fall 2019
- Lead instructor: [Katherine Fox-Glassman](mailto:kjt2111@columbia.edu)

### Course details

- Upper-level undergraduate class, required for the psychology major
- Approximately 70 students in the entire class, with lab sections of approximately 15 students

### Instructional responsibilities

- Updated course materials
  - Wrote 2 new R lesson plans and 2 new associated problem sets
  - Updated and annotated existing lesson plan outlines for each lab class
  - Created slide decks for each lab class
- Taught lab section
- Graded assignments
  - Exam short-answer questions (for all students)
  - Methods problem sets in R (for students in my section)
  - Science writing assignments and projects (for students in my section)
  - Individual and group presentations (for students in my section)
- Held weekly office hours
- Wrote short-answer exam questions

---

# Bootcamp instructor

## Foundations for Research Computing coding bootcamp

- Institution: Columbia University
- Terms: fall 2019, spring 2020, winter 2022
- Coordinator: [Patrick Smyth](mailto:website@pbsmyth.com)

### Course details

- Open-enrollment workshop hosted by Columbia Libraries for graduate students and postdocs across the university
- 30 students per session (in-person), 50 students per session (online)
- Associated with [The Carpentries](https://carpentries.org)

### Instructional responsibilities

- Delivered live-code lecture sessions introducing students to basic file navigation commands in Unix shell (1 3-hour session per workshop)

---

# Teaching assistant

## BUSI B8144 -- Intro to Programming in R

- Institution: Columbia University
- Terms: spring 2019, spring 2020, fall 2021
- Lead instructor: [Jared Lander](mailto:jaredlander@caa.columbia.edu)

### Course details

- Master’s level half-semester elective course in the business school
- Lecture class with 40-70 students depending on the term

### Instructional responsibilities

- Updated course materials
  - Revised existing problem sets to align objectives with lecture content
  - Re-implemented problem sets using learnr for students to complete exercises online
- Graded and gave written feedback on R problem sets
- Held weekly office hours
- Supported students’ work over email

---

## PSYC 1001: Science of Psychology

- Institution: Columbia University
- Term: fall 2017
- Lead instructor: [Kathleen Taylor](mailto:ktaylor@barnard.edu)

### Course details

- Intro-level undergraduate class, satisfies core science requirement for non-majors
- Approximately 100 students

### Instructional responsibilities

- Graded exam essays
- Wrote multiple-choice and essay exam questions
- Held weekly office hours
- Delivered guest lecture on memory
